# Generated by Django 2.0 on 2017-12-04 03:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0002_auto_20171204_0326'),
        ('pdm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartLive',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('QR_Code', models.CharField(blank=True, max_length=256, null=True, verbose_name='二维码')),
                ('Part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdm.Part', verbose_name='零件')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200, verbose_name='名称')),
                ('Tell', models.CharField(max_length=200, verbose_name='电话')),
                ('Address', models.CharField(blank=True, max_length=100, null=True, verbose_name='地址')),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org.Company', verbose_name='公司')),
            ],
        ),
    ]
