# Generated by Django 2.0 on 2017-12-13 06:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCon',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Status', models.CharField(blank=True, max_length=100, null=True, verbose_name='状态')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否生效')),
                ('Head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store', verbose_name='上一级仓库')),
            ],
        ),
        migrations.CreateModel(
            name='StoreConPartLive',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Number', models.IntegerField(default=0, verbose_name='数量')),
                ('PartLive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.PartLive', verbose_name='物料')),
                ('Store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store', verbose_name='仓库')),
            ],
        ),
    ]
