# Generated by Django 2.0 on 2017-12-13 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20171213_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecon',
            name='Head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HeadStore', to='store.Store', verbose_name='上一级仓库'),
        ),
        migrations.AlterField(
            model_name='storecon',
            name='Last',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LastStore', to='store.Store', verbose_name='下一级仓库'),
        ),
    ]
