# Generated by Django 2.0 on 2017-12-15 09:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20171213_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store_Status',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NO', models.CharField(max_length=20, unique=True, verbose_name='代码')),
                ('Name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '状态',
                'verbose_name_plural': '状态汇总',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='Status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store_Status', verbose_name='状态'),
        ),
    ]
