# Generated by Django 2.0 on 2017-12-15 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20171215_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='Status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store_Status', verbose_name='类型'),
        ),
    ]
