# Generated by Django 2.0 on 2017-12-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_storecontemp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storecontemp',
            name='Store',
        ),
        migrations.DeleteModel(
            name='StoreConTemp',
        ),
    ]
