# Generated by Django 2.0 on 2017-12-20 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20171220_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='R_Store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Rel_Store', to='store.Store', verbose_name='关联仓库'),
        ),
    ]
