# Generated by Django 2.0 on 2017-12-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_store_r_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='R_Store',
        ),
    ]
