# Generated by Django 2.0 on 2017-12-27 02:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_store_r_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Status',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NO', models.CharField(max_length=20, unique=True, verbose_name='代码')),
                ('Name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '类型',
                'verbose_name_plural': '类型汇总',
            },
        ),
        migrations.CreateModel(
            name='StoreForm',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20, verbose_name='名称')),
                ('Status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Form_Status', verbose_name='类型')),
                ('Store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Store', to='store.Store', verbose_name='仓库')),
            ],
        ),
        migrations.CreateModel(
            name='StoreFormConPartLive',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Number', models.IntegerField(default=0, verbose_name='数量')),
                ('PartLive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.PartLive', verbose_name='物料')),
                ('StoreForm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.StoreForm', verbose_name='表单')),
            ],
        ),
        migrations.AlterModelOptions(
            name='store_status',
            options={'verbose_name': '类型', 'verbose_name_plural': '类型汇总'},
        ),
    ]
