# Generated by Django 2.0 on 2017-12-27 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20171227_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeform',
            name='Store',
        ),
        migrations.AddField(
            model_name='storeform',
            name='Target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Target', to='store.Store', verbose_name='目标仓库'),
        ),
    ]
