# Generated by Django 2.0 on 2017-12-27 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20171227_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeform',
            name='Stored',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Store', to='store.Store', verbose_name='仓库'),
        ),
    ]
