# Generated by Django 2.0 on 2017-12-27 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_storeform_stored'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeform',
            name='Stored',
        ),
        migrations.RemoveField(
            model_name='storeform',
            name='Target',
        ),
        migrations.AddField(
            model_name='storeform',
            name='OriginStore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OriginStore', to='store.Store', verbose_name='仓库'),
        ),
        migrations.AddField(
            model_name='storeform',
            name='TargetStore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TargetStore', to='store.Store', verbose_name='目标仓库'),
        ),
    ]
