# Generated by Django 2.0 on 2018-01-04 02:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20180104_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeform',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期'),
        ),
    ]
