# Generated by Django 2.0 on 2018-01-04 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20180104_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeform',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeform',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
    ]
