# Generated by Django 2.0 on 2018-01-04 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20180104_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeform',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='storeform',
            name='modified_date',
        ),
    ]
