# Generated by Django 2.0 on 2018-01-04 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20180104_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeform',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 4, 2, 30, 52, 869162), verbose_name='创建时间'),
        ),
    ]
