# Generated by Django 2.0 on 2018-01-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_storeform_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeform',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
