# Generated by Django 2.0 on 2018-01-04 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20180104_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeform',
            name='created_date',
        ),
    ]
