# Generated by Django 2.0 on 2018-01-04 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_storeform_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeform',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 4, 2, 33, 18, 476085), verbose_name='创建时间'),
        ),
    ]
