# Generated by Django 2.0 on 2018-01-04 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20180104_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeform',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
    ]
