# Generated by Django 2.0 on 2018-01-04 02:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20180104_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeform',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='storeform',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
    ]
