# Generated by Django 2.0 on 2018-01-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20180104_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeform',
            name='modified_date',
        ),
        migrations.AlterField(
            model_name='storeform',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
