# Generated by Django 2.0 on 2018-01-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20180104_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeform',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='storeform',
            name='modified_date',
        ),
    ]
