# Generated by Django 2.0 on 2018-01-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_auto_20180104_0534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partlive',
            options={'ordering': ['Part__ItemNO']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['Name']},
        ),
        migrations.AlterModelOptions(
            name='store_status',
            options={'ordering': ['NO'], 'verbose_name': '类型', 'verbose_name_plural': '类型汇总'},
        ),
        migrations.AlterModelOptions(
            name='storecon',
            options={'ordering': ['Head']},
        ),
        migrations.AlterModelOptions(
            name='storeconpartlive',
            options={'ordering': ['PartLive__Part__ItemNO']},
        ),
        migrations.AlterModelOptions(
            name='storeform',
            options={'ordering': ['OriginStore']},
        ),
        migrations.AlterModelOptions(
            name='storeformconpartlive',
            options={'ordering': ['StoreForm']},
        ),
    ]
