# Generated by Django 2.0 on 2017-12-18 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduleauthority',
            options={'verbose_name': '模块权限', 'verbose_name_plural': '模块权限汇总'},
        ),
        migrations.AlterModelOptions(
            name='moduleinterface',
            options={'verbose_name': '模块接口', 'verbose_name_plural': '模块接口汇总'},
        ),
    ]
