# Generated by Django 2.0 on 2018-01-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Message',
            new_name='Content',
        ),
    ]
