# Generated by Django 2.0 on 2018-01-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20180116_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['NO']},
        ),
    ]
