# Generated by Django 2.0 on 2018-01-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20180122_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulemenu',
            options={'ordering': ['Display_ICO'], 'verbose_name': '模块菜单', 'verbose_name_plural': '模块菜单汇总'},
        ),
    ]
