# Generated by Django 2.0 on 2018-01-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20180124_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='NO',
            field=models.CharField(max_length=20, unique=True, verbose_name='代码'),
        ),
    ]
