# Generated by Django 2.0 on 2017-12-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Design_Rate',
            field=models.FloatField(default=0.8, verbose_name='设计系数'),
        ),
        migrations.AddField(
            model_name='user',
            name='Ui_Color',
            field=models.CharField(default='contrast-fb', max_length=20, verbose_name='界面颜色'),
        ),
        migrations.AddField(
            model_name='user',
            name='Ui_Zoom',
            field=models.FloatField(default=0.8, verbose_name='界面缩放系数'),
        ),
    ]
