# Generated by Django 2.0 on 2017-12-15 10:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('org', '0002_auto_20171204_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityCompany',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Company', verbose_name='公司')),
                ('Modules', models.ManyToManyField(to='general.Module', verbose_name='模块')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorityRole',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Modules', models.ManyToManyField(to='general.Module', verbose_name='模块')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20, verbose_name='名称')),
                ('Company', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='org.Company', verbose_name='公司')),
            ],
        ),
        migrations.AddField(
            model_name='authorityrole',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Role', verbose_name='角色'),
        ),
    ]
