# Generated by Django 2.0 on 2018-01-08 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20171218_0243'),
        ('org', '0003_auto_20171215_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authoritycompany',
            name='Modules',
        ),
        migrations.AddField(
            model_name='authoritycompany',
            name='Modules',
            field=models.ForeignKey(default='b41a29669b93417da4aad3c2cbb47aeb', on_delete=django.db.models.deletion.CASCADE, to='general.Module', verbose_name='模块'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='authorityrole',
            name='Modules',
        ),
        migrations.AddField(
            model_name='authorityrole',
            name='Modules',
            field=models.ForeignKey(default='b41a29669b93417da4aad3c2cbb47aeb', on_delete=django.db.models.deletion.CASCADE, to='general.Module', verbose_name='模块'),
            preserve_default=False,
        ),
    ]
