# Generated by Django 2.0 on 2018-01-10 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_auto_20180108_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConCompany',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Company', verbose_name='公司')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='UserConRole',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Role', verbose_name='角色')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
