# Generated by Django 2.0 on 2018-01-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_userconcompany_userconrole'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserConCompany',
            new_name='User_Con_Company',
        ),
        migrations.RenameModel(
            old_name='UserConRole',
            new_name='User_Con_Role',
        ),
    ]
