# Generated by Django 2.0 on 2018-01-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_auto_20180110_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_con_company',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='user_con_company',
            name='User',
        ),
        migrations.DeleteModel(
            name='User_Con_Company',
        ),
    ]
