# Generated by Django 2.0 on 2018-01-15 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20171218_0243'),
        ('org', '0007_auto_20180110_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityUser',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Module', verbose_name='模块')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='角色')),
            ],
        ),
    ]
