# Generated by Django 2.0 on 2018-01-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_authorityuser'),
    ]

    operations = [

    ]
