# Generated by Django 2.0 on 2018-01-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0009_role_no'),
    ]

    operations = [

    ]
