# Generated by Django 2.0 on 2018-01-19 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0009_role_no'),
    ]

    operations = [

    ]
