# Generated by Django 2.0 on 2018-01-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0011_auto_20180119_0546'),
    ]

    operations = [

    ]
