# Generated by Django 2.0 on 2018-01-19 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0013_auto_20180119_0549'),
    ]

    operations = [

    ]
