# Generated by Django 2.0 on 2018-01-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0014_remove_role_no'),
        ('org', '0011_role_isroot'),
    ]

    operations = [
    ]
