# Generated by Django 2.0 on 2018-01-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0017_auto_20180122_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorityrole',
            name='ModuleMenu',
        ),
    ]
