# Generated by Django 2.0 on 2018-01-23 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20180123_1042'),
        ('org', '0019_authorityrole_modulemenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authoritycompany',
            name='Modules',
        ),
        migrations.AddField(
            model_name='authoritycompany',
            name='ModuleMenu',
            field=models.ForeignKey(default='2725a64e43fc453c8388c3e486ee4352', on_delete=django.db.models.deletion.CASCADE, to='general.ModuleMenu', verbose_name='模块目录'),
            preserve_default=False,
        ),
    ]
