# Generated by Django 2.0 on 2018-01-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0020_auto_20180123_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorityrole',
            name='NO',
            field=models.CharField(default='7', max_length=20, verbose_name='权限代码'),
        ),
    ]
