# Generated by Django 2.0 on 2018-01-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0021_authorityrole_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorityrole',
            name='NO',
            field=models.CharField(default='0', max_length=20, verbose_name='权限代码'),
        ),
    ]
