# Generated by Django 2.0 on 2018-01-25 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20180124_0529'),
        ('org', '0023_authoritycompany_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authoritycompany',
            options={'ordering': ['Company']},
        ),
        migrations.AlterModelOptions(
            name='authorityrole',
            options={'ordering': ['Role']},
        ),
        migrations.RemoveField(
            model_name='authorityuser',
            name='Modules',
        ),
        migrations.AddField(
            model_name='authorityuser',
            name='ModuleMenu',
            field=models.ForeignKey(default='949121e7c20343daa7eb46617764754e', on_delete=django.db.models.deletion.CASCADE, to='general.ModuleMenu', verbose_name='模块目录'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authorityuser',
            name='NO',
            field=models.CharField(default='0', max_length=20, verbose_name='权限代码'),
        ),
    ]
