# Generated by Django 2.0 on 2018-02-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0025_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Job_Number',
            field=models.CharField(default='000000000', max_length=20, verbose_name='工号'),
        ),
    ]
