# Generated by Django 2.0 on 2018-02-05 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0026_user_job_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='department_con',
            name='is_First',
            field=models.BooleanField(default=False, verbose_name='是否为站点管理员'),
        ),
        migrations.AlterField(
            model_name='authorityrole',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Role', verbose_name='岗位'),
        ),
        migrations.AlterField(
            model_name='role',
            name='Name',
            field=models.CharField(max_length=20, verbose_name='岗位名称'),
        ),
        migrations.AlterField(
            model_name='user_con_role',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Role', verbose_name='岗位'),
        ),
    ]
