# Generated by Django 2.0 on 2018-02-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0027_auto_20180205_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department_con',
            name='is_First',
        ),
    ]
