# Generated by Django 2.0 on 2018-02-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0028_remove_department_con_is_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_First',
            field=models.BooleanField(default=False, verbose_name='起点'),
        ),
    ]
