# Generated by Django 2.0 on 2018-02-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0029_department_is_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Avatar',
            field=models.ImageField(default='/general/assets/images/avatar/default.png', upload_to='', verbose_name='头像'),
        ),
    ]
