# Generated by Django 2.0 on 2018-02-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0031_auto_20180206_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Avatar',
            field=models.ImageField(default='/images/avatar/default.png', upload_to='', verbose_name='头像'),
        ),
    ]
