# Generated by Django 2.0 on 2018-02-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0032_auto_20180206_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='Type',
            field=models.CharField(default='0', max_length=20, verbose_name='类型'),
        ),
    ]
