# Generated by Django 2.0 on 2018-02-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0033_role_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='isRoot',
        ),
    ]
