# Generated by Django 2.0 on 2018-02-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0034_remove_role_isroot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='Type',
            new_name='Account_Type',
        ),
    ]
