# Generated by Django 2.0 on 2018-02-22 02:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0035_auto_20180209_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Type',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NO', models.CharField(default='0', max_length=20, verbose_name='类型代码')),
                ('Name', models.CharField(max_length=20, verbose_name='类型名称')),
            ],
        ),
    ]
