# Generated by Django 2.0 on 2018-02-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0037_auto_20180222_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_type',
            name='NO',
            field=models.CharField(default='0', max_length=20, unique=True, verbose_name='账户类型代码'),
        ),
    ]
