# Generated by Django 2.0 on 2018-02-22 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0038_auto_20180222_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='Account_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Account_Type', verbose_name='类型'),
        ),
    ]
