# Generated by Django 2.0 on 2018-02-24 09:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0039_auto_20180222_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role_Con_Department',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Department', verbose_name='部门')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Role', verbose_name='岗位')),
            ],
            options={
                'ordering': ['Role__Company'],
            },
        ),
    ]
