# Generated by Django 2.0 on 2018-03-01 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0041_user_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Con_Comapny',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Company', verbose_name='公司')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'ordering': ['Company'],
            },
        ),
    ]
