# Generated by Django 2.0 on 2018-03-01 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0042_user_con_comapny'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Con_Comapny',
            new_name='User_Con_Company',
        ),
    ]
