# Generated by Django 2.0 on 2018-03-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0043_auto_20180301_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Company',
        ),
    ]
