# Generated by Django 2.0 on 2018-03-07 05:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20180124_0529'),
        ('org', '0045_user_con_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityDepartment',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NO', models.CharField(default='0', max_length=20, verbose_name='权限代码')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Department', verbose_name='公司')),
                ('ModuleMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.ModuleMenu', verbose_name='模块目录')),
            ],
            options={
                'ordering': ['Department'],
            },
        ),
    ]
