# Generated by Django 2.0 on 2017-12-04 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org', '0002_auto_20171204_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DocNO', models.CharField(max_length=20, unique=True, verbose_name='资料号')),
                ('Name', models.CharField(max_length=20, verbose_name='名称')),
                ('FileName', models.CharField(max_length=100, verbose_name='地址')),
                ('Regtime', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('Updatetime', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('Rev', models.IntegerField(default=0, verbose_name='版本号')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否生效')),
            ],
            options={
                'verbose_name': '图纸',
                'verbose_name_plural': '图纸汇总',
            },
        ),
        migrations.CreateModel(
            name='DrawingSize',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20, verbose_name='名称')),
                ('Size', models.CharField(blank=True, max_length=20, null=True, verbose_name='尺寸')),
            ],
            options={
                'verbose_name': '图幅',
                'verbose_name_plural': '图幅汇总',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20, verbose_name='名称')),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org.Company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '材料',
                'verbose_name_plural': '材料汇总',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ItemNO', models.CharField(max_length=30, unique=True, verbose_name='物号')),
                ('DocNO', models.CharField(blank=True, max_length=30, null=True, verbose_name='资料号')),
                ('Name', models.CharField(max_length=200, verbose_name='名称')),
                ('EName', models.CharField(blank=True, max_length=100, null=True, verbose_name='英文名称')),
                ('Regtime', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('Updatetime', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('Weight', models.FloatField(default=0, verbose_name='重量')),
                ('Note', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('Rev', models.IntegerField(default=0, verbose_name='版本号')),
                ('isActive', models.BooleanField(default=True, verbose_name='是都生效')),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org.Company', verbose_name='公司')),
                ('DUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('Material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdm.Materials', verbose_name='材料')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品汇总',
            },
        ),
        migrations.CreateModel(
            name='PDM_Status',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NO', models.CharField(max_length=20, unique=True, verbose_name='代码')),
                ('Name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '状态',
                'verbose_name_plural': '状态汇总',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20, verbose_name='名称')),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org.Company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '单位',
                'verbose_name_plural': '单位汇总',
            },
        ),
        migrations.AddField(
            model_name='part',
            name='Status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdm.PDM_Status', verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='part',
            name='Unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdm.Units', verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='Size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdm.DrawingSize', verbose_name='图幅'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='Status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdm.PDM_Status', verbose_name='状态'),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('ItemNO', 'Company')},
        ),
    ]
