# Generated by Django 2.0 on 2017-12-11 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=256, null=True, verbose_name='名称')),
            ],
        ),
    ]
